repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.5.3
    hooks:
      - id: prettier
        files: ^script-test\.js$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.27.0
    hooks:
      - id: eslint
        files: ^script-test\.js$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        files: \.json$
      - id: check-yaml
        files: \.ya?ml$
      - id: trailing-whitespace
        files: ^script-test\.js$
      - id: end-of-file-fixer
        files: ^script-test\.js$
      - id: check-added-large-files

  - repo: https://github.com/antonbabenko/pre-commit-eslint-security
    rev: v1.3.0
    hooks:
      - id: eslint-security
        files: ^script-test\.js$ #se avessi scritto files: \.js$ gli hooks si applicherebbero a tutti i file js
